down_clues = {
1: "Kind of heart valve",
2: "Easily led astray",
3: "Rich dessert",
4: "Something to do",
5: "Map box",
6: "“Did my heart love till now?” speaker",
7: "Detach, as a dress pattern",
8: "Isn’t straight",
9: "Big stretch",
10: "Deeply regret",
11: "Mo. town",
12: "High winds",
13: "Honolulu-born singer",
14: "Go back for a second helping",
18: "A dandelion’s are called blowballs",
21: "Fox NFL analyst Aikman",
22: "“Ick!”",
23: "Fled",
25: "Future JD’s Exam",
26: "Mongolian Tent",
30: "Shaggy rug from 12-across",
32: "Kosovo neighbor: abbr.",
33: "Surfeit",
34: "How-to presentation",
35: "Bearing",
36: "Prominent New York City feature",
37: "Give a little",
38: "Not post-",
42: "Short dogs, for short",
44: "Like some scarves",
45: "Works out",
46: "Last family to keep a White House cow",
48: "Dangerous virus",
49: "Lennon love song",
50: "Twist",
51: "Fleet",
54: "Heated state",
55: "Large green moth",
56: "One may be choked back",
57: "Dedicatee of 49-down",
58: "__ alone: not to mention"
}
# for e in down_clues.items():
#     print(e)