down_clues = {
1: "Classic Pontiac muscle cars",
2: "Top-notch",
3: "“Divergent” films heroine",
4: "Greek god of love",
5: "Actress Richards",
6: "Clog-busting brand",
7: "“Area” floor covering",
8: "Prez on a fiver",
9: "Pants holder-upper",
10: "Justice replaced by Gorsuch",
11: "*Coastal North Carolina resort area",
12: "It’s not poetry",
13: "Macho guys",
18: "Jazz genre",
22: "Regarding",
24: "*Source of free drinks",
25: "Valley __, Pa",
27: "Business Magnate",
28: "Country star McEntire",
29: "*Seance prop",
30: "Ill. winter hours",
32: "Equal",
34: "Ticket remnant",
35: "Shy",
37: "Polish a manuscript",
38: "Dogie catcher",
41: "Take advantage of",
43: "Simba’s mate",
46: "Smashed into",
47: "Online players",
48: "Military academy student",
49: "Samuel of the Supreme Court",
51: "Desi of “I Love Lucy”",
52: "Bit of computer RAM",
54: "Gossip columnist Barrett",
56: "Theater award...and a phonetic hint to the answers to starred clues",
57: "Roam",
58: "Smack, as a fly",
59: "Cockney greeting",
62: "Stool pigeon",
63: "Big fuss"
}
# for e in down_clues.items():
#     print(e)