across_clues = {
1: "Analyze critically",
6: "Counting gadgets",
11: "Business address abbr.",
14: "Michener novel with astronauts",
15: "Answer an insult with an insult, say",
16: "Short flight",
17: "U.S. gaming release of 1989",
19: "It often follows you",
20: "Ivan or Nicholas",
21: "Actor Chaney",
22: "Windy home, probably",
24: "Chiffon-like materials",
28: "Left the country?",
31: "Piccadilly Circus statue",
32: "Plain text",
33: "Future first lady wed in 1842",
37: "It’s all around us",
38: "Hangs on a line?",
40: "Word from a bull",
41: "Foam toy",
44: "Line to the audience",
46: "Took the bus",
47: "Becomes a burden",
49: "Rocky Mountains nickname",
53: "Give a speech",
54: "Longing",
55: "Cheese with an edible rind",
59: "Beans or baloney",
60: "Simple salad...and what the starts of the five other longest answers are?",
64: "Aardvark snack",
65: "European women’s name meaning “peace”",
66: "Safe places?",
67: "Caustic chemical",
68: "State of northeast India",
69: "Temporarily unavailable"
}
# for e in across_clues.items():
#     print(e)