across_clues = {
1: "Like some private communities",
6: "Really dull",
10: "Second-year student",
14: "Ex-Yankee manager Joe",
15: "Goldberg who drew complex “machines”",
16: "Make healthy",
17: "*Bread with a schmear",
19: "__ Ant: tiny toon superhero",
20: "Therapy visit",
21: "“Honor Thy Father” author Gay",
23: "Parody",
26: "Fire engine signal",
27: "“Bad, Bad Leroy Brown” singer Jim",
31: "Can opener",
33: "Chief Greek god",
34: "Mono successor",
36: "__ Lingus",
39: "Somewhat",
40: "Hint of color",
41: "Escape key function",
42: "Friend of TV’s Sheldon and Leonard",
43: "“For my next __...”: singer’s intro",
44: "Pass over",
45: "“Laurence of __”",
47: "“Beau __”",
48: "Scheming group",
50: "Serious play",
53: "Roberto or Sandy of baseball",
55: "Deep regret",
60: "Line through the middle of a circle: Abbr.",
61: "*Annual Florida football game",
64: "To be, to Balzac",
65: "Mexican’s zilch",
66: "Primary foe",
67: "Lincoln in-law",
68: "From __: all inclusive",
69: "Take care of"
}
# for e in across_clues.items():
#     print(e)