across_clues = {
1: "Golden __",
5: "Soreness treatment",
15: "Russian region rich in minerals",
16: "Marketeer in the 1016 film “War Dogs”",
17: "It’s to be expected",
18: "Baroque chamber work",
19: "Prefix meaning “within”",
20: "Solo on-screen",
21: "Epithet for Tim",
22: "Attended to barking dogs",
23: "Bump-related",
27: "“One time 4 your mind” rapper",
28: "One may have its own tartan design",
30: "Adobe creation",
32: "Sitcom shoe salesman",
34: "Fauvism pioneer",
38: "Lively dances in duple time",
39: "Lusters",
40: "Test involving reading letters",
42: "Considers closely",
43: "The Cranberries vocalist O’Riordan",
45: "Trilogy, often",
46: "Super __",
49: "Meal involving charoseth, a symbolic fruit paste",
50: "Silent welcomer?",
51: "Narrow shore point",
53: "Boxer’s statement",
55: "Drought-stricken",
56: "Place with flexible classes",
60: "Get around?",
61: "Prying aid",
62: "“Radames’ Letter” musical",
63: "Film genre named for a supporting performer",
64: "Went like the wind"
}
for e in across_clues.items():
    print(e)