down_clues = {
1: "“Hey!”",
2: "Gibbons, e.g.",
3: "Music featuring sitars",
4: "Often colorful accessories",
5: "Neurologist’s printout, briefly",
6: "“Dover Beach” poet",
7: "__ Bag: eponymous ‘70s designer label",
8: "Remote batteries",
9: "Third century date",
10: "Delivery announcement",
11: "Puppeteer Lewis",
12: "Tire-shaped",
13: "They’re heavier than foils",
18: "Nobelist Wiesel",
23: "Once, old style",
25: "Poem of homage",
26: "Skillful deed",
27: "SFO postings",
28: "Time period",
29: "Buffalo’s county",
30: "Irish pop group family name",
33: "End of a corporal’s URL",
34: "Sapporo sashes",
35: "“Seriously, man”",
36: "Adds highlights to, perhaps",
38: "Arabian arroyo",
39: "Words after shake or break",
42: "Worry",
43: "Czech Republic region",
44: "Likely",
45: "Nutrient-rich legume",
47: "Winter eave buildup",
48: "“Merciless” Flash Gordon foe",
49: "Story lesson",
50: "Device common on “Seinfeld”",
51: "Starbuck’s order",
52: "Spotted African predator",
56: "OPTI-FREE rival",
57: "Contents of many cartridges",
58: "To be, to Brutus",
61: "Apr. Adressee",
62: "Crosses (out)",
63: "Slugger’s stat"
}
for e in down_clues.items():
    print(e)