down_clues = {
1: "Online role-playing game involving magical stones",
2: "Steel for one",
3: "Bridge site",
4: "Saint in a Brat Pack title",
5: "Old ownership word",
6: "Misjudgement",
7: "Key with all white notes",
8: "Chicken general",
9: "Lab coat attachments",
10: "“The Matrix” hero",
11: "Thomas Wolfe alter ego Eugene",
12: "Bagel choice",
13: "Insurance giant",
14: "Horse-drawn wagons",
24: "Abby title",
25: "Humiliates",
26: "Metal working tool",
29: "Heated quickly",
30: "Certain agency goal",
31: "Levels",
33: "Greek island known for emery",
35: "Cooking agent in some Indian cuisine",
36: "Hitchhike successfully",
37: "Attorney’s specialty",
41: "Change, briefly, as game software",
42: "Water in a green bottle",
44: "Text file with instructions",
46: "“Fooled you!”",
47: "Ohno on skates",
48: "Relaxing smoke for some",
52: "Shooting marbles",
54: "__ song",
55: "Sign of healing",
57: "Goose, e.g.",
58: "Asian path",
59: "One making calls at home"
}
# for e in down_clues.items():
#     print(e)