across_clues = {
1: "VMI Program",
5: "'80s-’90s courtroom drama",
10: "On-call worker",
14: "Assert as true",
15: "Three-time A.L. batting champ Tony",
16: "Pupils place",
17: "Chipper",
20: "Tetra-doubled",
21: "Atonement",
22: "Confuse",
25: "Wrigley brand",
27: "Chipper",
31: "Geological time span",
32: "Carpenter’s joint element",
33: "Hiccup cause",
36: "Genesis voyager",
38: "Protector with strings",
40: "Mlle., across the Pyrenees",
41: "God of Islam",
43: "Called from the field",
45: "Bordeaux vineyard",
46: "Chipper",
49: "Rural wagons",
50: "Response at the door",
51: "Fair hiring problem",
54: "“I don’t like your __”",
56: "Chipper",
62: "Tierra en el mar",
63: "Force to leave",
64: "Personification of victory",
65: "Dance basic",
66: "Shemar’s longtime “Criminal Minds” role",
67: "Plus"
}
# for e in across_clues.items():
#     print(e)