down_clues = {
1: "One of five characters on “The Big Bang Theory” to appear in every episode",
2: "Ab __: from the start",
3: "Cube root of 1,000",
4: "Spicy cuisine",
5: "Plunder",
6: "Italian wheels, briefly",
7: "Ad-__",
8: "Director DuVernay",
9: "Horseradish relative",
10: "Casual summer garments",
11: "Former Indiana governor Bayh",
12: "Amalgamate",
13: "Chums",
18: "Crime scene clue, maybe",
19: "Arab bigwigs",
22: "Gemini rocket stage",
23: "Eagerly anticipate, with “over”",
24: "North America’s highest peak",
25: "Fragrant",
26: "Fame",
28: "Large expanse",
29: "Part of the picture",
30: "Busters",
34: "Four-decades-plus first name in the Senate",
35: "Title role for Bea",
37: "Links equalizer",
39: "Take-home",
42: "Tough to hear, as criticism",
44: "Like embers",
47: "Stuck",
48: "Medit. tourist attraction",
51: "Author Martin",
52: "Unexpected blow",
53: "Couture monthly",
54: "Roof piece",
55: "Fraction of a meg",
57: "Men’s grooming brand",
58: "Aperitif named for a former Dijon mayor",
59: "Good thing to strike",
60: "Signs off on",
61: "Sign of summer"
}
# for e in down_clues.items():
#     print(e)