
down_clues = {
    1: "Brittanica ref.",
    4: "Singer LuPone",
9: "Baseball hat",
12: "Classic Grape Soda",
14: "Sarge’s command",
15: "Put into play",
16: "Advice columnists Ann and Abby, e.g. (AL Central)",
18: "If I may digress…,” in texts",
19: "Sprinted",
20: "Jackie’s Ari",
22: "__ one’s time: didn’t rush",
23: "Sharp-tasting",
24: "King’s tenure",
27: "Tiered Asian temple",
30: "Apt’s sleeping area",
33: "“Bro!”",
35: "Hitch as a ride",
36: "Commit purjury",
37: "Monarch’s self-referential plural pronoun (AL Central)",
39: "Shop __ you drop",
40: "“The Giant” of wrestling",
42: "Food for hogs",
43: "“Ohio” quartet, initially",
44: "St. Peter’s domain",
45: "“The Lion King” hero",
48: "Chinese PC Giant whose name is partly derived from the Latin for “new”",
50: "Hertz rival",
53: "Faddish pursuit, after all",
55: "Carefree antics",
58: "“The Fault in __ Stars”: 2014 film",
59: "Pride or greed, e.g. (NL Central)",
61: "Obtain",
62: "Neatened (up)",
63: "Chekov bridgemate, in “Star Trek”",
64: "GEICO specialties?",
65: "Little cuts",
66: "Org. in which the start of five answers is a “central” player"

}
