down_clues = {
1: "Noble",
11: "Tic __: mints",
15: "Play with unseen players",
16: "Buck Heroine",
17: "Certain clinic contributor",
18: "Hall of Fame quarterback Graham",
19: "Significant span",
20: "Satirized",
21: "Kind of list",
22: "Homework shirkers comeuppance",
24: "It may hold broken pottery",
25: "Hilarious",
26: "Frozen beverages",
28: "Source of blowups",
29: "They’re off-limits",
30: "Olympic figure skating gold medalist after Kristi",
32: "Makes a lot of progress",
34: "Many an Irish song",
36: "Try for a better hand",
37: "Smirks",
40: "Stir to action",
44: "Mystical views",
45: "Saddle-making tool",
47: "Muesli brand",
48: "Constellation points",
49: "Musician Lennon",
51: "Banjo bar",
52: "Barbarian horde",
53: "It includes AAPL and MSFT",
55: "Devoured with “up”",
56: "Thrill from Sills",
57: "Start",
59: "Steal, perhaps",
60: "Dropped in on",
61: "Mrs. Krabappel of “The Simpsons”",
62: "Giovanni Ribisi title con man"
}
# for e in down_clues.items():
#     print(e)