across_clues = {1: "__\'acte: intermission", 
    2: "A novice in", 3: "Trouser material",
    4: "Kid brother, at times",
5: "Colony crawler",
6: "2000s teen drama set in California",
7: "Rutabaga, e.g.",
8: "Tryst-confirming words",
9: "Preteens in a pack (NL Central)",
10: "Italian wine hub",
11: "Chapel seats",
13: "Bring up to speed",
14: "\"__ the season...\"",
17: "Sushi bar drink",
21: "[Ah, me!]",
23: "\"Furthermore...\"",
25: "Altar promise",
26: "Five __: burger chain",
28: "Key with one flat: Abbr.",
29: "With dexterity",
30: "\"How dull\"",
31: "Enjoy fine food",
32: "Warnings of serious danger (NL Central)",
34: "Wells sci-fi race",
37: "Performs in costume, as a Civil War battle",
38: "Typist’s meas.",
41: "KOA patron",
43: "Nitpicks",
45: "Consequence of an absence of pain, in an exercise mantra",
47: "Mexicali’s peninsula",
49: "\"Rigoletto\" composer",
51: "\"To wrap up...\"",
52: "Proficiency",
53: "Frat party garb",
54: "Tinted",
55: "Makes haste, old-style",
56: "Swing voter: Abbr.",
57: "Cold shoulder",
60: "Quick swim"

}
